# Generated by Django 5.1.5 on 2025-01-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='education',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='resume',
        ),
    ]
